// 旅遊清單：分類、行李位置、預設模板（來源：Notion「Ultimate Travel Kit」2026-07-16 快照，見 spec 附錄A）
// 純資料模組——node 可直接 import 驗證（tests/checklist-data.test.mjs）；改模板改這裡再發版

export const CHECKLIST_CATEGORIES = [
    { slug: 'docs', label: '證件財物', emoji: '🛂' },
    { slug: 'tech', label: '3C', emoji: '🔌' },
    { slug: 'meds', label: '藥品', emoji: '💊' },
    { slug: 'toiletry', label: '盥洗保養', emoji: '🧴' },
    { slug: 'makeup', label: '彩妝', emoji: '💄' },
    { slug: 'clothes', label: '衣物鞋帽', emoji: '👕' },
    { slug: 'flight', label: '機上舒適', emoji: '✈️' },
    { slug: 'misc', label: '雜物', emoji: '🧷' },
];

export const LUGGAGE_META = {
    carry: { label: '隨身', cls: 'bg-green-50 text-green-600 border-green-100' },
    any: { label: '不限', cls: 'bg-stone-100 text-stone-500 border-stone-200' },
    checked: { label: '託運', cls: 'bg-red-50 text-red-500 border-red-100' },
};

// [category, name, luggage, note]
const T = [
    ['docs', '護照 (有效期限>6個月)', 'carry', '絕對不可託運'],
    ['docs', '簽證 / 入境許可證明', 'carry', '紙本備份 + 電子檔'],
    ['docs', '身份證 (備用)', 'carry', '國內段或遺失護照時用'],
    ['docs', '信用卡 (海外回饋高)', 'carry', '建議帶兩張不同發卡組織'],
    ['docs', '當地貨幣 (現金)', 'carry', '小額面額為主'],
    ['docs', '台幣 (回程車資)', 'carry', ''],
    ['docs', '網卡 / SIM卡 / 取卡針', 'carry', '落地即用'],
    ['docs', '旅遊保險單 (英文版)', 'carry', '醫療證明用'],
    ['docs', '飯店訂房確認單', 'carry', '地址與電話'],
    ['docs', '原子筆 (黑/藍)', 'carry', '填寫入境卡專用'],
    ['tech', '手機', 'carry', ''],
    ['tech', '行動電源 (Power Bank)', 'carry', '⚠️ 嚴禁託運'],
    ['tech', '筆記型電腦 / 平板', 'carry', '鋰電池建議隨身'],
    ['tech', '相機機身', 'carry', '貴重物品'],
    ['tech', '記憶卡 (SD Card)', 'carry', '建議多備一張'],
    ['tech', '充電線 (Type-C)', 'carry', ''],
    ['tech', '充電線 (Lightning)', 'carry', ''],
    ['tech', '降噪耳機', 'carry', '機上與通勤救星'],
    ['tech', '萬國轉接頭', 'any', '建議帶有多孔USB的'],
    ['tech', '智慧手錶充電器', 'any', '容易遺忘的小物'],
    ['tech', '腳架 / 自拍棒', 'checked', '管徑/長度通常需託運'],
    ['meds', '個人常備藥 (處方籤)', 'carry', '需保留藥袋說明'],
    ['meds', '暈車 / 暈機藥', 'carry', '搭乘前30分鐘服用'],
    ['meds', '止痛藥 (EVE/普拿疼)', 'any', '頭痛經痛用'],
    ['meds', '腸胃藥 / 益生菌', 'any', '水土不服必備'],
    ['meds', '止瀉藥', 'any', ''],
    ['meds', '感冒藥 / 綜合維他命', 'any', '增強抵抗力'],
    ['meds', 'OK繃 / 外傷藥膏', 'checked', '磨腳時也可用'],
    ['toiletry', '牙刷 / 牙膏', 'checked', '環保旅館可能不提供'],
    ['toiletry', '牙線 / 牙線棒', 'checked', ''],
    ['toiletry', '洗面乳', 'checked', ''],
    ['toiletry', '洗髮精 / 潤髮乳', 'checked', ''],
    ['toiletry', '沐浴乳 (旅行組)', 'checked', ''],
    ['toiletry', '卸妝油 / 卸妝水', 'checked', '液體>100ml需託運'],
    ['toiletry', '化妝水 (Toner)', 'checked', ''],
    ['toiletry', '精華液 (Serum)', 'checked', ''],
    ['toiletry', '乳液 / 乳霜', 'checked', '機艙乾燥需加強保濕'],
    ['toiletry', '面膜 (保濕型)', 'checked', '救急修護用'],
    ['toiletry', '防曬乳 (臉部)', 'any', '隨身瓶需<100ml'],
    ['toiletry', '防曬噴霧/乳 (身體)', 'checked', '高壓瓶罐需留意法規'],
    ['toiletry', '護唇膏', 'carry', ''],
    ['toiletry', '護手霜', 'carry', ''],
    ['toiletry', '刮鬍刀 (手動/電動)', 'checked', '刀片類建議託運'],
    ['toiletry', '指甲剪', 'checked', '⚠️ 視為利器，不可隨身'],
    ['toiletry', '止汗劑 / 體香膏', 'checked', ''],
    ['toiletry', '棉花棒 / 化妝棉', 'checked', ''],
    ['toiletry', '生理食鹽水 / 保養液', 'checked', ''],
    ['toiletry', '隱形眼鏡 (日拋/雙週)', 'any', '隨身帶一副備用'],
    ['toiletry', '月亮杯/月亮碟片', 'any', ''],
    ['makeup', '妝前乳 / 隔離霜', 'checked', ''],
    ['makeup', '粉底液 / 氣墊粉餅', 'checked', ''],
    ['makeup', '遮瑕膏', 'checked', ''],
    ['makeup', '眉筆 / 染眉膏', 'checked', ''],
    ['makeup', '眼影盤', 'checked', '易碎品需包好'],
    ['makeup', '眼線筆 / 睫毛膏', 'checked', ''],
    ['makeup', '腮紅 / 修容 / 打亮', 'checked', ''],
    ['makeup', '定妝噴霧 / 蜜粉', 'checked', ''],
    ['makeup', '口紅 / 唇釉', 'any', '隨身帶一支補妝'],
    ['clothes', '上衣 (T-shirt/襯衫)', 'checked', '依穿搭計畫'],
    ['clothes', '下著 (褲/裙)', 'checked', ''],
    ['clothes', '內衣褲 (天數+1)', 'checked', '建議使用壓縮袋'],
    ['clothes', '襪子 (天數+1)', 'checked', ''],
    ['clothes', '睡衣 / 居家服', 'checked', ''],
    ['clothes', '外套 / 風衣', 'any', '機上/早晚溫差大'],
    ['clothes', '好走的鞋 (球鞋)', 'carry', '日行萬步關鍵'],
    ['clothes', '拖鞋 / 涼鞋', 'checked', '飯店內或海邊用'],
    ['clothes', '帽子', 'checked', '造型與遮陽'],
    ['clothes', '太陽眼鏡', 'carry', ''],
    ['flight', '頸枕 (充氣式佳)', 'carry', '長途飛行必備'],
    ['flight', '眼罩', 'carry', '阻絕機艙光線'],
    ['flight', '耳塞', 'carry', '阻絕引擎聲/嬰兒聲'],
    ['misc', '折疊傘 / 雨衣', 'checked', '隨身需看安檢規定'],
    ['misc', '髒衣收納袋', 'checked', '乾濕分離'],
    ['misc', '夾鏈袋 (Ziploc)', 'checked', '收納零碎小物'],
    ['misc', '環保購物袋', 'carry', '裝戰利品用'],
];

export const CHECKLIST_TEMPLATE = T.map(([category, name, luggage, note]) => ({ category, name, luggage, note }));
